### ISSUE TITLE
Is it possible to disable scrolling within HTML component instead use scroll of parent scrollview

### ISSUE THREAD

**Issue by msuma268** [native-html/table-plugin#19]
I used this library as shown in the example and was able to render HTMLs with table tags as expected. However, if HTML is wrapped with Scrollview then there are 2 scrolls shown on the UI (one for parent Scrollview and the other for the Webview). 

Is it possible to hide scroll of Webview and instead use Scroll of parent view i.e, ScrollView?

**Comment by jsamr** [comment]
@msuma268 Good question, that could be added in a FAQ. Can you share a small reproduction [with a snack](https://snack.expo.io)? That will help me help you :-)

**Comment by jsamr** [comment]
@msuma268 I suggest you disable horizontal scrolling from the parent ScrollView with `horizontal: false` prop. Closing now! Don't hesitate to reply if you have any question regarding this issue.
