### ISSUE TITLE
How can i change the style for table?

### ISSUE THREAD

**Issue by BogdanRad** [native-html/table-plugin#23]
@jsamr How can i set the background color transparent and remove the border? Thanks!

I have to make it in this form
![image](https://user-images.githubusercontent.com/40359109/89868100-ee803100-dbba-11ea-9537-b9cd91fd1f93.png).

And now my design is:
![image](https://user-images.githubusercontent.com/40359109/89868152-02c42e00-dbbb-11ea-803c-cb7c4f902a7b.png)

**Comment by jsamr** [comment]
@BogdanRad See https://github.com/native-html/table-plugin#tablestylespecs

**Comment by BogdanRad** [comment]
@jsamr can you give me an example please? 
here is my code, but don't working...
![image](https://user-images.githubusercontent.com/40359109/89878392-280c6880-dbca-11ea-941e-d9274aefac53.png)

**Comment by jsamr** [comment]
@BogdanRad I'm willing to help, but I would need you to create a snack first, so that I can reproduce the issue consistently. I suggest you start from our snack template here: https://snack.expo.io/@jsamr/rnrhtml-template, and you can post the link when you're ready.

**Comment by BogdanRad** [comment]
Thanks @jsamr . I updated the link: https://snack.expo.io/0Ei30zf1B

**Comment by jsamr** [comment]
@BogdanRad Perhaps it is just an omission. But you are not passing the config to the HTML component, so there is no chances the rendering can work! Have you tried your snack on the expo app for iOS / Android?

```jsx
<HTML html={html} />
```
with
```jsx
<HTML html={html} {...htmlConfig} />
```

**Comment by BogdanRad** [comment]
I updated the link. I added htmlConfig to <HTML /> but doesn't working.. the style doesn't change. 
Is it ok how I add in config?

**Comment by jsamr** [comment]
@BogdanRad You are absolutely right. I'm looking into it and publishing a pre-release soon.

**Comment by jsamr** [comment]
@BogdanRad Actually I am wrong! The library just work as expected. You misunderstood (and I didn't realize) that the tableStyleSpecs is an attribut **of the `makeTableRenderer` config parameter**.

So you can now do instead:

```jsx
import * as React from 'react';
import {ScrollView, StyleSheet} from 'react-native';
import HTML from 'react-native-render-html';
import WebView from 'react-native-webview';
import {
  IGNORED_TAGS,
  alterNode,
  makeTableRenderer,
} from 'react-native-render-html-table-bridge';

const html = `
<table>
  <tr>
    <td><b>Culoare</b></td>
    <td>Negru</td>
  </tr>
  <tr>
    <td><b>Material</b></td>
    <td>Silicon</td>
  </tr>
  <tr>
    <td><b>Tip</b></td>
    <td>Carcasa</td>
  </tr>
  <tr>
    <td><b>Telefon compatibil</b></td>
    <td>Galaxy S20 Plus</td>
  </tr>
</table>
`;

const config = {
  WebViewComponent: WebView,
  tableStyleSpecs: {
    borderWidthPx: 0,
    thOddBackground: 'transparent',
    thEvenBackground: 'transparent',
    trOddBackground: 'transparent',
    trEvenBackground: 'transparent',
    thEvenColor: '#000000',
    trOddColor: '#000000',
    thOddColor: '#000000',
    trEvenColor: '#000000',
  },
};

const renderers = {
  table: makeTableRenderer(config),
};

const htmlConfig = {
  alterNode,
  renderers,
  ignoredTags: IGNORED_TAGS,
};

export default function App() {
  return (
    <ScrollView style={{flex: 1}} contentContainerStyle={styles.container}>
      <HTML style={{flex: 1}} html={html} {...htmlConfig} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 0,
    backgroundColor: 'red',
  },
});
```
Next time, take the time to read the documentation.
